# Generated by Django 4.0.2 on 2022-02-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_amenity_options_alter_facility_options_and_more'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='room',
        ),
        migrations.AddField(
            model_name='list',
            name='room',
            field=models.ManyToManyField(blank=True, to='rooms.Room'),
        ),
    ]
