# Generated by Django 4.0.2 on 2022-02-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='houserule',
            options={'verbose_name_plural': 'House rules'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Room types'},
        ),
    ]
